/* Scientifically qualified natural-context data for the element modal.
   Percentages are mass fractions unless the atmosphere line explicitly says volume. */
const crustMgKg=[1400,.008,20,2.8,10,200,19,461000,585,.005,23600,23300,82300,282000,1050,350,145,3.5,20900,41500,22,5650,120,102,950,56300,25,84,60,70,19,1.5,1.8,.05,2.4,.0001,90,370,33,165,20,1.2,null,.001,.001,.015,.075,.15,.25,2.3,.2,.001,.45,.00003,3,425,39,66.5,9.2,41.5,null,7.05,2,6.2,1.2,5.2,1.3,3.5,.52,3.2,.8,3,2,1.25,.0007,.0015,.001,.005,.004,.085,.85,14,.0085,2e-10,null,4e-13,null,9e-7,5.5e-10,9.6,1.4e-6,2.7,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];
/* Asplund et al. 2021-style photospheric log epsilon values; null means no defensible
   stable photospheric determination. Values are converted below to approximate mass %. */
const solarLog=[12,10.93,0.96,1.38,2.70,8.46,7.83,8.69,4.40,8.06,6.22,7.55,6.43,7.51,5.41,7.12,5.31,6.38,5.07,6.30,3.14,4.97,3.90,5.62,5.42,7.46,4.94,6.20,4.18,4.56,3.02,3.62,2.30,3.34,2.54,3.12,2.32,2.83,2.21,2.59,1.47,1.88,null,1.75,.78,1.57,.96,1.71,.80,2.02,1.01,2.18,1.55,2.22,1.08,2.27,1.11,1.58,.75,1.42,null,.95,.52,1.08,.31,1.10,.48,.93,.11,.85,.10,.85,-.15,.79,.26,1.35,1.32,1.61,.91,1.17,.90,1.95,.65,null,null,null,null,null,null,.03,null,-.54,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];
while(crustMgKg.length<118)crustMgKg.push(null);
while(solarLog.length<118)solarLog.push(null);
solarLog.length=118;
const atomicWeights=elements.map(e=>parseFloat(e.mass)||e.z*2.45);
const solarRaw=solarLog.map((x,i)=>x==null?0:Math.pow(10,x-12)*atomicWeights[i]);
const solarDen=solarRaw.reduce((a,b)=>a+b,0);
const solarPct=solarRaw.map(x=>100*x/solarDen);

const naturalProfiles={
 H:['water, organic matter, hydrocarbons and stars','O in water; C in organic matter and hydrocarbons; N and S in biomolecules','acqua, materia organica, idrocarburi e stelle','O nell’acqua; C nella materia organica e negli idrocarburi; N e S nelle biomolecole'],
 He:['natural gas, the atmosphere and radioactive minerals; continually lost to space','normally monatomic; trapped with natural gas rather than chemically bonded','gas naturale, atmosfera e minerali radioattivi; viene continuamente disperso nello spazio','normalmente monoatomico; intrappolato con il gas naturale, non legato chimicamente'],
 Li:['spodumene, lepidolite and continental brines','O and Si in silicates; Cl in brines','spodumene, lepidolite e salamoie continentali','O e Si nei silicati; Cl nelle salamoie'],
 Be:['beryl and chrysoberyl','O and Si in beryl; O and Al in chrysoberyl','berillo e crisoberillo','O e Si nel berillo; O e Al nel crisoberillo'],
 B:['borax, kernite, borate brines and plant tissue','O in borates; Na and Ca in evaporite minerals','borace, kernite, salamoie boratiche e tessuti vegetali','O nei borati; Na e Ca nei minerali evaporitici'],
 C:['living matter, carbonates, fossil fuels, graphite and diamond','H, O and N in biology; Ca/Mg in carbonates; Fe in carbides','materia vivente, carbonati, combustibili fossili, grafite e diamante','H, O e N nella biologia; Ca/Mg nei carbonati; Fe nei carburi'],
 N:['mainly atmospheric N₂; also nitrates, ammonia and biomolecules','H in ammonia and proteins; O in nitrates; C in organic matter','soprattutto N₂ atmosferico; anche nitrati, ammoniaca e biomolecole','H nell’ammoniaca e nelle proteine; O nei nitrati; C nella materia organica'],
 O:['air, water, silicate rocks, oxides and living matter','H in water; Si, Al, Fe, Ca and Mg in rocks; C in CO₂ and carbonates','aria, acqua, rocce silicatiche, ossidi e materia vivente','H nell’acqua; Si, Al, Fe, Ca e Mg nelle rocce; C in CO₂ e carbonati'],
 F:['fluorite, fluorapatite and cryolite','Ca in fluorite/apatite; Na and Al in cryolite','fluorite, fluorapatite e criolite','Ca in fluorite/apatite; Na e Al nella criolite'],
 Ne:['trace monatomic gas in the atmosphere and gases released from rocks','normally monatomic; essentially no stable natural compounds','gas monoatomico in tracce nell’atmosfera e nei gas liberati dalle rocce','normalmente monoatomico; praticamente nessun composto naturale stabile'],
 Na:['halite, seawater, evaporites and silicate minerals','Cl in halite/seawater; O and Si in feldspars and clays','halite, acqua marina, evaporiti e minerali silicatici','Cl nell’halite e nell’acqua marina; O e Si in feldspati e argille'],
 Mg:['seawater, dolomite, magnesite, olivine and chlorophyll','O and Si in silicates; C/O in carbonates; N in chlorophyll','acqua marina, dolomite, magnesite, olivina e clorofilla','O e Si nei silicati; C/O nei carbonati; N nella clorofilla'],
 Al:['feldspars, clays, micas and bauxite; never native in ordinary environments','O and Si in aluminosilicates; O in bauxite minerals','feldspati, argille, miche e bauxite; non nativo negli ambienti ordinari','O e Si negli alluminosilicati; O nei minerali della bauxite'],
 Si:['quartz, feldspars, clays and nearly all common silicate rocks','O overwhelmingly; Al, Mg, Fe, Ca, Na and K in silicates','quarzo, feldspati, argille e quasi tutte le comuni rocce silicatiche','soprattutto O; Al, Mg, Fe, Ca, Na e K nei silicati'],
 P:['apatite and phosphate rock; DNA, ATP, bones and teeth','O and Ca in phosphates; O/H/C/N in living systems','apatite e rocce fosfatiche; DNA, ATP, ossa e denti','O e Ca nei fosfati; O/H/C/N nei sistemi viventi'],
 S:['native sulfur, sulfides, sulfates, volcanic gases and proteins','Fe, Cu, Zn and Pb in sulfides; O/Ca in sulfates; C/H in biology','zolfo nativo, solfuri, solfati, gas vulcanici e proteine','Fe, Cu, Zn e Pb nei solfuri; O/Ca nei solfati; C/H nella biologia'],
 Cl:['seawater, halite and evaporite brines; as chloride, not free Cl₂','Na, K, Mg and Ca as chlorides; H in gastric HCl','acqua marina, halite e salamoie evaporitiche; come cloruro, non Cl₂ libero','Na, K, Mg e Ca come cloruri; H nell’HCl gastrico'],
 Ar:['monatomic gas in air, much of it radiogenic ⁴⁰Ar from ⁴⁰K','normally monatomic; trapped in fluids, rocks and ice','gas monoatomico nell’aria, in gran parte ⁴⁰Ar radiogenico da ⁴⁰K','normalmente monoatomico; intrappolato in fluidi, rocce e ghiaccio'],
 K:['feldspars, micas, sylvite, seawater and cells','O/Si/Al in silicates; Cl in sylvite; organic ligands in cells','feldspati, miche, silvite, acqua marina e cellule','O/Si/Al nei silicati; Cl nella silvite; ligandi organici nelle cellule'],
 Ca:['limestone, marble, gypsum, apatite, shells and bones','C/O in carbonates; S/O in gypsum; P/O in apatite','calcare, marmo, gesso, apatite, conchiglie e ossa','C/O nei carbonati; S/O nel gesso; P/O nell’apatite'],
 Fe:['iron oxides, sulfides, silicates, meteorites, Earth’s core and heme','O in hematite/magnetite; S in pyrite; Ni in metal; C/N/S in proteins','ossidi, solfuri, silicati, meteoriti, nucleo terrestre ed eme','O in ematite/magnetite; S nella pirite; Ni nel metallo; C/N/S nelle proteine'],
 Cu:['chalcopyrite and other sulfides, oxides and rare native copper','S and Fe in sulfide ores; O/C in oxidized ores; proteins in organisms','calcopirite e altri solfuri, ossidi e raro rame nativo','S e Fe nei minerali solforati; O/C nei minerali ossidati; proteine negli organismi'],
 Zn:['sphalerite, smithsonite and zinc-bearing proteins','S in sphalerite; C/O in smithsonite; N/S/O ligands in enzymes','sfalerite, smithsonite e proteine contenenti zinco','S nella sfalerite; C/O nella smithsonite; ligandi N/S/O negli enzimi'],
 Br:['seawater and concentrated evaporite brines, almost entirely as Br⁻','Na, K, Mg and Ca in dissolved bromide salts','acqua marina e salamoie evaporitiche concentrate, quasi tutto come Br⁻','Na, K, Mg e Ca nei bromuri disciolti'],
 I:['seawater, marine organisms, iodate/iodide brines and thyroid hormones','Na/K as iodides or iodates; C in thyroid hormones','acqua marina, organismi marini, salamoie con iodato/ioduro e ormoni tiroidei','Na/K come ioduri o iodati; C negli ormoni tiroidei'],
 U:['uraninite, carnotite, phosphate rocks and trace amounts in seawater','O in uranyl minerals; V/K in carnotite; Pb as radiogenic decay product','uraninite, carnotite, rocce fosfatiche e tracce nell’acqua marina','O nei minerali uranilici; V/K nella carnotite; Pb come prodotto radiogenico']
};

const familyProfiles={
 noble:['a trace monatomic gas in air or gases trapped in rocks','normally monatomic; compounds are absent or exceptional','gas monoatomico in tracce nell’aria o intrappolato nelle rocce','normalmente monoatomico; i composti sono assenti o eccezionali'],
 alkali:['silicate minerals, evaporites or natural brines; never as free metal','O/Si in minerals and halides in salts','minerali silicatici, evaporiti o salamoie naturali; mai come metallo libero','O/Si nei minerali e alogeni nei sali'],
 alkaline:['carbonate, sulfate or silicate minerals; never as free metal','O with C, S or Si in common minerals','minerali carbonatici, solfatici o silicatici; mai come metallo libero','O con C, S o Si nei minerali comuni'],
 transition:['oxide, sulfide or silicate ores, commonly associated with other transition metals','O, S and sometimes C/As; metal–metal association in ores and alloys','minerali ossidati, solforati o silicatici, spesso associato ad altri metalli di transizione','O, S e talvolta C/As; associazioni metallo–metallo in minerali e leghe'],
 post:['sulfide or oxide ores, commonly recovered with Zn, Pb or Cu','S and O; frequent geological association with Zn, Pb or Cu','minerali solforati o ossidati, spesso recuperato insieme a Zn, Pb o Cu','S e O; frequente associazione geologica con Zn, Pb o Cu'],
 metalloid:['oxide, sulfide or silicate minerals rather than the free element','O and S; Si/metal partners depend on the mineral','minerali ossidati, solforati o silicatici anziché l’elemento libero','O e S; i partner Si/metallo dipendono dal minerale'],
 nonmetal:['minerals, volatile compounds or biological matter, depending on the element','O and H are frequent natural partners; mineral hosts are element-specific','minerali, composti volatili o materia biologica, secondo l’elemento','O e H sono partner naturali frequenti; i minerali ospiti dipendono dall’elemento'],
 halogen:['halide or oxyanion salts in minerals, seawater or brines; not as free diatomic element','Na, K, Ca and Mg in salts; O in oxyanions','sali alogenuri o ossoanioni in minerali, acqua marina o salamoie; non come elemento biatomico libero','Na, K, Ca e Mg nei sali; O negli ossoanioni'],
 lanth:['monazite, bastnäsite, xenotime or related rare-earth ores','O, F and P in mixed rare-earth minerals','monazite, bastnäsite, xenotime o minerali affini delle terre rare','O, F e P nei minerali misti delle terre rare'],
 act:['uranium/thorium minerals or minute products of radioactive decay','O in oxides/uranyl minerals; decay-chain association with Pb, Ra or U','minerali di uranio/torio o prodotti in quantità minime del decadimento radioattivo','O negli ossidi/minerali uranilici; associazione di catena con Pb, Ra o U']
};

const atmosphere={H:['variable H₂O; H₂ ≈0.55 ppm by volume','H₂O variabile; H₂ ≈0,55 ppm in volume'],He:['≈5.24 ppm by volume in dry air','≈5,24 ppm in volume nell’aria secca'],C:['CO₂ ≈0.042% by volume; CH₄ ≈1.92 ppm (variable)','CO₂ ≈0,042% in volume; CH₄ ≈1,92 ppm (variabile)'],N:['N₂ 78.084% by volume of dry air; plus trace N₂O/NOₓ','N₂ 78,084% in volume dell’aria secca; più tracce di N₂O/NOₓ'],O:['O₂ 20.946% by volume of dry air; also variable H₂O/CO₂','O₂ 20,946% in volume dell’aria secca; anche H₂O/CO₂ variabili'],Ne:['≈18.18 ppm by volume in dry air','≈18,18 ppm in volume nell’aria secca'],Ar:['≈0.934% by volume in dry air','≈0,934% in volume nell’aria secca'],Kr:['≈1.14 ppm by volume in dry air','≈1,14 ppm in volume nell’aria secca'],Xe:['≈0.09 ppm by volume in dry air','≈0,09 ppm in volume nell’aria secca']};

function fmtPct(v,lang){if(!v)return lang==='it'?'non quantificabile':'not quantifiable';let s=v>=.1?v.toFixed(3):v>=.001?v.toPrecision(3):v.toExponential(2);return (lang==='it'?s.replace('.',','):s)+'%';}
function fmtCrust(v,lang){if(v==null)return lang==='it'?'nessuna abbondanza naturale misurabile':'no measurable natural abundance';const qualifier=lang==='it'?' in massa':' by mass';if(v>=10000)return fmtPct(v/10000,lang)+qualifier;const amount=lang==='it'?String(v).replace('.',','):String(v);return amount+' ppm'+qualifier;}
function elementProfile(e,lang){
 const synthetic=e.z>=104, shortLived=[43,61,85,87,93,94,95,96,97,98,99,100,101,102,103].includes(e.z);
 let p=naturalProfiles[e.symbol]||familyProfiles[e.cat]||familyProfiles.transition;
 if(synthetic)p=lang==='it'?['prodotto atomo per atomo in acceleratori; nessuna presenza naturale confermata','nessun “partner naturale”: esiste solo per tempi brevissimi prima del decadimento']:['made atom-by-atom in accelerators; no confirmed natural occurrence','no “natural partners”: it exists only briefly before radioactive decay'];
 const occurrence=synthetic?p[0]:(lang==='it'?p[2]:p[0]), partners=synthetic?p[1]:(lang==='it'?p[3]:p[1]);
 const crust=fmtCrust(crustMgKg[e.z-1],lang);
 const air=atmosphere[e.symbol]?.[lang==='it'?1:0]||(lang==='it'?'nessuna frazione gassosa stabile e ben mescolata; solo aerosol o composti locali variabili':'no stable well-mixed gaseous fraction; only variable local aerosols or compounds');
 const sun=solarLog[e.z-1]==null?(lang==='it'?'non determinabile nella fotosfera':'not determinable in the photosphere'):('≈'+fmtPct(solarPct[e.z-1],lang)+' '+(lang==='it'?'in massa, fotosfera':'by mass, photosphere'));
 const proto=solarLog[e.z-1]==null?(lang==='it'?'nessun valore protosolare affidabile':'no reliable protosolar value'):('≈'+fmtPct(solarPct[e.z-1]*(e.z===1?.99:e.z===2?1.05:1.12),lang)+' '+(lang==='it'?'in massa; riferimento protosolare/meteoritico':'by mass; protosolar/meteoritic reference'));
 const universe=solarLog[e.z-1]==null?(lang==='it'?'nessuna percentuale cosmica naturale significativa':'no meaningful natural cosmic percentage'):e.symbol==='H'?(lang==='it'?'≈74% della materia ordinaria, in massa':'≈74% of ordinary matter by mass'):e.symbol==='He'?(lang==='it'?'≈24% della materia ordinaria, in massa':'≈24% of ordinary matter by mass'):('ordine di grandezza ≈'+fmtPct(solarPct[e.z-1],lang)+'; '+(lang==='it'?'proxy del vicinato solare, non media esatta dell’Universo':'solar-neighbourhood proxy, not an exact Universe-wide mean'));
 const note=synthetic?(lang==='it'?'Le proprietà chimiche sono in parte previste da pochi atomi e decadimenti rapidi.':'Chemistry is partly inferred from very few atoms and rapid decays.'):shortLived?(lang==='it'?'Radioattivo e raro: la presenza naturale, se esiste, deriva da decadimento o fissione.':'Radioactive and rare: natural occurrence, where present, comes from decay or fission.'):(lang==='it'?'Le associazioni indicate descrivono ospiti naturali comuni, non tutti i composti possibili.':'The associations name common natural hosts, not every compound the element can form.');
 return{occurrence,partners,crust,air,sun,proto,universe,note};
}
