Object.assign(IT, {
  'Oxidation and reduction are coupled half-reactions. The species oxidized loses electrons and its oxidation number increases; the species reduced gains electrons and its oxidation number decreases. Electrons must cancel when the half-reactions are added.': 'Ossidazione e riduzione sono semireazioni accoppiate. La specie ossidata perde elettroni e aumenta il proprio numero di ossidazione; quella ridotta acquista elettroni e lo diminuisce. Gli elettroni devono cancellarsi sommando le semireazioni.',
  'Look for changing oxidation numbers, elemental O₂, metals becoming ions, combustion, electrochemical cells or corrosion.': 'Cerca variazioni dei numeri di ossidazione, O₂ elementare, metalli che diventano ioni, combustioni, celle elettrochimiche o corrosione.',
  'Zn + Cu²⁺ → Zn²⁺ + Cu; combustion of methane; rusting of iron; electron flow in a battery.': 'Zn + Cu²⁺ → Zn²⁺ + Cu; combustione del metano; arrugginimento del ferro; flusso di elettroni in una batteria.',
  'Contact may be enough, but heat, light, an external voltage, an electrolyte or a catalyst can determine rate and direction.': 'Il contatto può bastare, ma calore, luce, tensione esterna, elettrolita o catalizzatore possono determinare velocità e direzione.',
  'A Brønsted–Lowry acid donates a proton (H⁺); a base accepts it. Products are the conjugate base and conjugate acid. In water, free H⁺ is represented more realistically as hydronium, H₃O⁺.': 'Un acido di Brønsted–Lowry cede un protone (H⁺); una base lo accetta. I prodotti sono la base coniugata e l’acido coniugato. In acqua H⁺ è rappresentato più realisticamente come idronio, H₃O⁺.',
  'Identify transferable H atoms and species with lone pairs or negative charge. Acid–base reactions need not involve OH⁻.': 'Individua atomi di H trasferibili e specie con doppietti non condivisi o carica negativa. Le reazioni acido–base non richiedono necessariamente OH⁻.',
  'HCl + H₂O → H₃O⁺ + Cl⁻; CH₃COOH + HCO₃⁻; antacids; buffer systems.': 'HCl + H₂O → H₃O⁺ + Cl⁻; CH₃COOH + HCO₃⁻; antiacidi; sistemi tampone.',
  'The solvent, concentration, acid/base strength and temperature control equilibria; gas formation can drive a reaction forward.': 'Solvente, concentrazione, forza di acido e base e temperatura controllano gli equilibri; la formazione di gas può spingere avanti la reazione.',
  'In metathesis, ions exchange partners without necessarily changing oxidation state. A net reaction occurs when one product leaves the ionic mixture as a precipitate, gas or weakly ionized molecular substance such as water.': 'Nella metatesi gli ioni scambiano partner senza cambiare necessariamente numero di ossidazione. Si ha reazione netta quando un prodotto lascia la miscela come precipitato, gas o sostanza molecolare poco ionizzata, come l’acqua.',
  'Start with soluble ionic compounds, dissociate strong electrolytes, cancel spectator ions and write the net ionic equation.': 'Parti dai composti ionici solubili, dissocia gli elettroliti forti, elimina gli ioni spettatori e scrivi l’equazione ionica netta.',
  'Reactants are commonly mixed in solution. Solubility rules, concentration and pH determine whether a precipitate forms.': 'I reagenti vengono normalmente mescolati in soluzione. Regole di solubilità, concentrazione e pH determinano la formazione del precipitato.',
  'This broad family changes the covalent or ionic framework: combination makes fewer products, decomposition makes more, and substitution replaces one atom or group. Polymerization repeatedly links monomers.': 'Questa famiglia modifica l’ossatura covalente o ionica: la combinazione produce meno prodotti, la decomposizione ne produce di più e la sostituzione rimpiazza un atomo o gruppo. La polimerizzazione collega ripetutamente monomeri.',
  'Track which bonds are broken and formed. A balanced equation reports stoichiometry, not the molecular mechanism or transition state.': 'Segui i legami rotti e formati. Un’equazione bilanciata descrive la stechiometria, non il meccanismo molecolare né lo stato di transizione.',
  '2 H₂ + O₂ → 2 H₂O; CaCO₃ → CaO + CO₂; ethene → polyethylene; halogen substitution.': '2 H₂ + O₂ → 2 H₂O; CaCO₃ → CaO + CO₂; etene → polietilene; sostituzione con alogeni.',
  'Heat, photons, pressure, radical initiators, acids, bases or catalysts may supply activation energy or select a pathway.': 'Calore, fotoni, pressione, iniziatori radicalici, acidi, basi o catalizzatori possono fornire energia di attivazione o selezionare un percorso.',
  'A low-voltage DC source drives a non-spontaneous redox reaction. Hydrogen forms at the cathode and oxygen at the anode; ideal collected volumes approach 2:1 because 2 H₂O → 2 H₂ + O₂.': 'Una sorgente continua a bassa tensione forza una reazione redox non spontanea. Al catodo si forma idrogeno e all’anodo ossigeno; i volumi ideali tendono a 2:1 perché 2 H₂O → 2 H₂ + O₂.',
  'Red-cabbage extract contains anthocyanins whose molecular forms—and colors—depend on pH. Household samples produce a qualitative acidic-to-alkaline scale.': 'L’estratto di cavolo rosso contiene antociani le cui forme molecolari, e quindi i colori, dipendono dal pH. Campioni domestici producono una scala qualitativa da acido ad alcalino.',
  'Acetic acid transfers a proton to bicarbonate. Carbonic acid forms transiently and decomposes to water and carbon dioxide; the escaping gas produces visible fizzing.': 'L’acido acetico trasferisce un protone al bicarbonato. Si forma temporaneamente acido carbonico, che si decompone in acqua e anidride carbonica; il gas produce l’effervescenza.',
  'Iron is oxidized to Fe²⁺ while Cu²⁺ is reduced to copper metal: Fe(s) + Cu²⁺(aq) → Fe²⁺(aq) + Cu(s). Copper deposits on the cleaned iron surface.': 'Il ferro si ossida a Fe²⁺ mentre Cu²⁺ si riduce a rame metallico: Fe(s) + Cu²⁺(aq) → Fe²⁺(aq) + Cu(s). Il rame si deposita sulla superficie pulita del ferro.',
  'Cooling or evaporation can make a saturated solution supersaturated. Solute particles then nucleate and add to an ordered lattice; slower growth often yields larger crystals.': 'Raffreddamento o evaporazione possono rendere sovrasatura una soluzione satura. Le particelle nucleano e si aggiungono a un reticolo ordinato; una crescita lenta produce spesso cristalli più grandi.',
  'A catalyst provides a lower-activation-energy pathway for 2 H₂O₂ → 2 H₂O + O₂. Detergent traps oxygen as foam; the catalyst changes rate but is not consumed overall.': 'Un catalizzatore offre un percorso a minore energia di attivazione per 2 H₂O₂ → 2 H₂O + O₂. Il detergente intrappola l’ossigeno nella schiuma; il catalizzatore modifica la velocità ma non viene consumato nel bilancio complessivo.',
  'It demonstrates electrode half-reactions, atom conservation and conversion of electrical energy into chemical energy.': 'Dimostra le semireazioni agli elettrodi, la conservazione degli atomi e la conversione di energia elettrica in energia chimica.',
  'It makes acid–base equilibria visible; it is qualitative and does not replace a calibrated pH meter.': 'Rende visibili gli equilibri acido–base; è qualitativo e non sostituisce un pHmetro calibrato.',
  'It connects proton transfer, gas evolution and the role of product removal as a driving force.': 'Collega trasferimento protonico, sviluppo di gas e rimozione di un prodotto come forza motrice.',
  'It makes coupled electron transfer and relative metal reactivity directly observable.': 'Rende direttamente osservabili il trasferimento elettronico accoppiato e la reattività relativa dei metalli.',
  'It links macroscopic crystal shape to solubility, nucleation and microscopic periodic order.': 'Collega la forma macroscopica dei cristalli a solubilità, nucleazione e ordine periodico microscopico.',
  'It distinguishes kinetics from stoichiometric yield and reveals an exothermic catalytic process.': 'Distingue la cinetica dalla resa stechiometrica e mostra un processo catalitico esotermico.',
  'Low-voltage DC · inert electrodes': 'Corrente continua a bassa tensione · elettrodi inerti','Electricity': 'Elettricità','Red cabbage · household samples': 'Cavolo rosso · campioni domestici','Mixing': 'Miscelazione','Vinegar · sodium bicarbonate': 'Aceto · bicarbonato di sodio','Iron · dilute CuSO₄ solution': 'Ferro · soluzione diluita di CuSO₄','Contact': 'Contatto','Table salt or alum · water': 'Sale da cucina o allume · acqua','Cooling / evaporation': 'Raffreddamento / evaporazione','3% H₂O₂ · detergent · yeast': 'H₂O₂ al 3% · detergente · lievito','Catalyst': 'Catalizzatore',
  'Add a small amount of inert electrolyte to water in a transparent vessel.': 'Aggiungi all’acqua una piccola quantità di elettrolita inerte in un recipiente trasparente.','Insert two inert electrodes without letting them touch.': 'Inserisci due elettrodi inerti senza farli toccare.','Connect to a current-limited DC source and collect the gases separately in inverted water-filled tubes.': 'Collega una sorgente continua a corrente limitata e raccogli separatamente i gas in provette capovolte piene d’acqua.','Compare gas volumes; interpret with the balanced equation.': 'Confronta i volumi dei gas e interpretali mediante l’equazione bilanciata.',
  'Steep chopped red cabbage in hot water, cool and filter the purple extract.': 'Lascia il cavolo rosso tritato in acqua calda, raffredda e filtra l’estratto viola.','Place equal portions in labeled clear cups.': 'Distribuisci porzioni uguali in bicchieri trasparenti etichettati.','Add one separate sample per cup, such as lemon juice, water or bicarbonate solution.': 'Aggiungi un solo campione per bicchiere, per esempio succo di limone, acqua o soluzione di bicarbonato.','Record colors against a control; do not return tested liquids to containers.': 'Confronta i colori con il controllo; non riversare i liquidi nei contenitori originali.',
  'Place a measured spoonful of sodium bicarbonate in a wide container.': 'Metti una quantità misurata di bicarbonato di sodio in un contenitore largo.','Add a measured small volume of vinegar.': 'Aggiungi un piccolo volume misurato di aceto.','Observe fizzing and, optionally, capture CO₂ in a loosely fitted balloon.': 'Osserva l’effervescenza e, facoltativamente, raccogli la CO₂ in un palloncino applicato senza tenuta rigida.','Write the molecular and net ionic descriptions; compare initial and final mass only in a properly designed closed system.': 'Scrivi l’equazione molecolare e quella ionica netta; confronta le masse solo in un sistema chiuso progettato correttamente.',
  'Clean an iron nail with abrasive material and record its appearance.': 'Pulisci un chiodo di ferro con materiale abrasivo e annotane l’aspetto.','Immerse it in a labeled dilute copper(II) sulfate solution.': 'Immergilo in una soluzione diluita ed etichettata di solfato di rame(II).','Wait without stirring, then compare coating and solution color.': 'Attendi senza agitare, poi confronta il deposito e il colore della soluzione.','Remove with forceps, rinse into the waste container and dispose through an approved route.': 'Rimuovi con pinze, risciacqua nel contenitore dei rifiuti e smaltisci secondo una procedura approvata.',
  'Add solute gradually to hot water until a small amount no longer dissolves.': 'Aggiungi gradualmente il soluto all’acqua calda finché una piccola quantità non si scioglie più.','Decant or filter the clear saturated solution into a clean jar.': 'Travasa o filtra la soluzione satura limpida in un vaso pulito.','Suspend a seed crystal or rough thread without touching the walls.': 'Sospendi un cristallo-seme o un filo ruvido senza toccare le pareti.','Cover loosely, leave undisturbed and record growth over several days.': 'Copri senza sigillare, lascia indisturbato e registra la crescita per alcuni giorni.',
  'Place the open bottle or cylinder in a tray and add a little dish detergent.': 'Metti il recipiente aperto in un vassoio e aggiungi poco detersivo per piatti.','Prepare a yeast suspension in lukewarm water as the catalase source.': 'Prepara una sospensione di lievito in acqua tiepida come fonte di catalasi.','Add the suspension and step back from the rising foam.': 'Aggiungi la sospensione e allontanati dalla schiuma in crescita.','Feel warmth only indirectly at the vessel exterior; relate O₂ production to the balanced equation.': 'Rileva il calore soltanto indirettamente sulla parete esterna; collega la produzione di O₂ all’equazione bilanciata.'
});

Object.assign(IT, {
  'Use a current-limited low-voltage source; never use mains electricity or ignite collected gas.':'Usa una sorgente a bassa tensione con corrente limitata; mai la rete elettrica e mai incendiare i gas raccolti.',
  'Do not mix household cleaners with one another; especially never combine bleach with acids or ammonia.':'Non mescolare detergenti domestici fra loro; soprattutto mai candeggina con acidi o ammoniaca.',
  'Use small quantities in an open container; never cap or seal a gas-producing mixture.':'Usa piccole quantità in un contenitore aperto; non chiudere mai una miscela che produce gas.',
  'Copper sulfate is harmful to people and aquatic life; use a controlled protocol and collect all waste.':'Il solfato di rame è nocivo per persone e vita acquatica; usa un protocollo controllato e raccogli tutti i rifiuti.',
  'Use heat-resistant glassware and protect against hot water; crystals are not food after laboratory handling.':'Usa vetreria resistente al calore e proteggiti dall’acqua calda; dopo l’esperimento i cristalli non sono commestibili.',
  'Use only household 3% peroxide, small quantities, eye protection and an open tray; the vessel may warm.':'Usa soltanto perossido domestico al 3%, piccole quantità, protezione oculare e un vassoio aperto; il recipiente può scaldarsi.',
  'First classify':'Prima classifica','Ionic: formula → name':'Ionico: formula → nome','Ionic: name → formula':'Ionico: nome → formula','Variable-charge metals':'Metalli a carica variabile','Molecular: formula → name':'Molecolare: formula → nome','Molecular: name → formula':'Molecolare: nome → formula','Acids':'Acidi','Hydrates and states':'Idrati e stati fisici',
  'Metal + non-metal or polyatomic ion?':'Metallo + non metallo o ione poliatomico?','Two non-metals?':'Due non metalli?','Formula begins H and is aqueous? Often an':'La formula inizia con H ed è acquosa? Spesso è un','This first decision chooses the naming system.':'Questa prima decisione determina il sistema di nomenclatura.',
  'Read the cation, then the anion. Monatomic anions take':'Leggi prima il catione, poi l’anione. Gli anioni monoatomici prendono','Keep polyatomic names unchanged:':'Mantieni invariati i nomi degli ioni poliatomici:','No numerical prefixes.':'Nessun prefisso numerico.',
  'Write ion charges, then choose the lowest subscripts giving net charge zero:':'Scrivi le cariche ioniche, poi scegli i minimi pedici che danno carica netta zero:','Use parentheses when several polyatomic ions are needed:':'Usa le parentesi quando occorrono più ioni poliatomici:',
  'Infer metal charge from the anion and state it as a Roman numeral:':'Ricava la carica del metallo dall’anione e indicala con un numero romano:','Iron(II) oxide would be FeO.':'L’ossido di ferro(II) sarebbe FeO.',
  'Use prefixes for atom counts; normally omit mono- on the first element.':'Usa i prefissi per il numero di atomi; normalmente ometti mono- sul primo elemento.','The second element takes -ide:':'Il secondo elemento assume il suffisso appropriato:','Prefixes become subscripts directly—never “balance charges”:':'I prefissi diventano direttamente pedici: non “bilanciare le cariche”:','The (aq) state matters.':'Lo stato (aq) è determinante.','State symbols:':'Simboli di stato:','solid':'solido','liquid':'liquido','gas':'gas','dissolved in water':'disciolto in acqua.'
});

function bondClarifier() {
  const box = document.getElementById('molinfo');
  if (!box || box.querySelector('.bond-clarifier')) return;
  const it = document.getElementById('language').value === 'it';
  const acid = selected.fam === 'Acids';
  const ionic = selected.bond === 'ionic';
  let en, ita;
  if (acid) {
    en = '<b>Why are no bonds drawn here?</b> An acid formula does not by itself specify the physical state. Pure HCl, HNO₃ or H₂SO₄ are molecular substances with covalent bonds; in water they transfer protons to H₂O and form solvated ions to an extent that depends on acid strength. A single ball-and-stick picture would therefore conflate the pure molecular species with the aqueous ionic system.';
    ita = '<b>Perché qui non sono disegnati legami?</b> La formula di un acido non specifica da sola lo stato fisico. HCl, HNO₃ o H₂SO₄ puri sono sostanze molecolari con legami covalenti; in acqua trasferiscono protoni a H₂O e formano ioni solvatati in misura dipendente dalla forza dell’acido. Un unico modello a sfere confonderebbe quindi la specie molecolare pura con il sistema ionico acquoso.';
  } else if (ionic) {
    en = '<b>Why are no individual ionic bonds drawn?</b> This formula describes the smallest electrically neutral ratio in an extended crystal lattice, not a discrete molecule. Each ion interacts electrostatically with several neighbours; drawing one isolated pair would be misleading.';
    ita = '<b>Perché non sono disegnati singoli legami ionici?</b> La formula descrive il minimo rapporto elettricamente neutro in un reticolo cristallino esteso, non una molecola discreta. Ogni ione interagisce elettrostaticamente con più vicini; disegnare una coppia isolata sarebbe fuorviante.';
  } else {
    en = '<b>Why is there no bond network?</b> The molecular formula fixes elemental composition but may correspond to different constitutional isomers, stereoisomers or extended structures. Unless a verified structure is encoded, this atlas shows exact composition and deliberately does not invent connectivity or bond order.';
    ita = '<b>Perché non compare una rete di legami?</b> La formula molecolare fissa la composizione elementare ma può corrispondere a diversi isomeri costituzionali, stereoisomeri o strutture estese. Se non è codificata una struttura verificata, l’atlante mostra la composizione esatta e non inventa connettività o ordine di legame.';
  }
  box.insertAdjacentHTML('beforeend', `<div class="scientific-note bond-clarifier">${it ? ita : en}</div>`);
}

new MutationObserver(() => bondClarifier()).observe(document.getElementById('molinfo'), {childList:true});
bondClarifier();
document.getElementById('language').addEventListener('change', () => {
  document.querySelector('.bond-clarifier')?.remove();
  bondClarifier();
  setTimeout(() => translateTree(), 0);
});
