Object.assign(IT, {
  'Oxidation and reduction are coupled half-reactions. The species oxidized loses electrons and its oxidation number increases; the species reduced gains electrons and its oxidation number decreases. Electrons must cancel when the half-reactions are added.': 'Ossidazione e riduzione sono semireazioni accoppiate. La specie ossidata perde elettroni e aumenta il proprio numero di ossidazione; quella ridotta acquista elettroni e lo diminuisce. Gli elettroni devono cancellarsi sommando le semireazioni.',
  'Look for changing oxidation numbers, elemental O₂, metals becoming ions, combustion, electrochemical cells or corrosion.': 'Cerca variazioni dei numeri di ossidazione, O₂ elementare, metalli che diventano ioni, combustioni, celle elettrochimiche o corrosione.',
  'Zn + Cu²⁺ → Zn²⁺ + Cu; combustion of methane; rusting of iron; electron flow in a battery.': 'Zn + Cu²⁺ → Zn²⁺ + Cu; combustione del metano; arrugginimento del ferro; flusso di elettroni in una batteria.',
  'Contact may be enough, but heat, light, an external voltage, an electrolyte or a catalyst can determine rate and direction.': 'Il contatto può bastare, ma calore, luce, tensione esterna, elettrolita o catalizzatore possono determinare velocità e direzione.',
  'A Brønsted–Lowry acid donates a proton (H⁺); a base accepts it. Products are the conjugate base and conjugate acid. In water, free H⁺ is represented more realistically as hydronium, H₃O⁺.': 'Un acido di Brønsted–Lowry cede un protone (H⁺); una base lo accetta. I prodotti sono la base coniugata e l’acido coniugato. In acqua H⁺ è rappresentato più realisticamente come idronio, H₃O⁺.',
  'Identify transferable H atoms and species with lone pairs or negative charge. Acid–base reactions need not involve OH⁻.': 'Individua atomi di H trasferibili e specie con doppietti non condivisi o carica negativa. Le reazioni acido–base non richiedono necessariamente OH⁻.',
  'HCl + H₂O → H₃O⁺ + Cl⁻; CH₃COOH + HCO₃⁻; antacids; buffer systems.': 'HCl + H₂O → H₃O⁺ + Cl⁻; CH₃COOH + HCO₃⁻; antiacidi; sistemi tampone.',
  'The solvent, concentration, acid/base strength and temperature control equilibria; gas formation can drive a reaction forward.': 'Solvente, concentrazione, forza di acido e base e temperatura controllano gli equilibri; la formazione di gas può spingere avanti la reazione.',
  'In metathesis, ions exchange partners without necessarily changing oxidation state. A net reaction occurs when one product leaves the ionic mixture as a precipitate, gas or weakly ionized molecular substance such as water.': 'Nella metatesi gli ioni scambiano partner senza cambiare necessariamente numero di ossidazione. Si ha reazione netta quando un prodotto lascia la miscela come precipitato, gas o sostanza molecolare poco ionizzata, come l’acqua.',
  'Start with soluble ionic compounds, dissociate strong electrolytes, cancel spectator ions and write the net ionic equation.': 'Parti dai composti ionici solubili, dissocia gli elettroliti forti, elimina gli ioni spettatori e scrivi l’equazione ionica netta.',
  'Reactants are commonly mixed in solution. Solubility rules, concentration and pH determine whether a precipitate forms.': 'I reagenti vengono normalmente mescolati in soluzione. Regole di solubilità, concentrazione e pH determinano la formazione del precipitato.',
  'This broad family changes the covalent or ionic framework: combination makes fewer products, decomposition makes more, and substitution replaces one atom or group. Polymerization repeatedly links monomers.': 'Questa famiglia modifica l’ossatura covalente o ionica: la combinazione produce meno prodotti, la decomposizione ne produce di più e la sostituzione rimpiazza un atomo o gruppo. La polimerizzazione collega ripetutamente monomeri.',
  'Track which bonds are broken and formed. A balanced equation reports stoichiometry, not the molecular mechanism or transition state.': 'Segui i legami rotti e formati. Un’equazione bilanciata descrive la stechiometria, non il meccanismo molecolare né lo stato di transizione.',
  '2 H₂ + O₂ → 2 H₂O; CaCO₃ → CaO + CO₂; ethene → polyethylene; halogen substitution.': '2 H₂ + O₂ → 2 H₂O; CaCO₃ → CaO + CO₂; etene → polietilene; sostituzione con alogeni.',
  'Heat, photons, pressure, radical initiators, acids, bases or catalysts may supply activation energy or select a pathway.': 'Calore, fotoni, pressione, iniziatori radicalici, acidi, basi o catalizzatori possono fornire energia di attivazione o selezionare un percorso.',
  'A low-voltage DC source drives a non-spontaneous redox reaction. Hydrogen forms at the cathode and oxygen at the anode; ideal collected volumes approach 2:1 because 2 H₂O → 2 H₂ + O₂.': 'Una sorgente continua a bassa tensione forza una reazione redox non spontanea. Al catodo si forma idrogeno e all’anodo ossigeno; i volumi ideali tendono a 2:1 perché 2 H₂O → 2 H₂ + O₂.',
  'Red-cabbage extract contains anthocyanins whose molecular forms—and colors—depend on pH. Household samples produce a qualitative acidic-to-alkaline scale.': 'L’estratto di cavolo rosso contiene antociani le cui forme molecolari, e quindi i colori, dipendono dal pH. Campioni domestici producono una scala qualitativa da acido ad alcalino.',
  'Acetic acid transfers a proton to bicarbonate. Carbonic acid forms transiently and decomposes to water and carbon dioxide; the escaping gas produces visible fizzing.': 'L’acido acetico trasferisce un protone al bicarbonato. Si forma temporaneamente acido carbonico, che si decompone in acqua e anidride carbonica; il gas produce l’effervescenza.',
  'Iron is oxidized to Fe²⁺ while Cu²⁺ is reduced to copper metal: Fe(s) + Cu²⁺(aq) → Fe²⁺(aq) + Cu(s). Copper deposits on the cleaned iron surface.': 'Il ferro si ossida a Fe²⁺ mentre Cu²⁺ si riduce a rame metallico: Fe(s) + Cu²⁺(aq) → Fe²⁺(aq) + Cu(s). Il rame si deposita sulla superficie pulita del ferro.',
  'Cooling or evaporation can make a saturated solution supersaturated. Solute particles then nucleate and add to an ordered lattice; slower growth often yields larger crystals.': 'Raffreddamento o evaporazione possono rendere sovrasatura una soluzione satura. Le particelle nucleano e si aggiungono a un reticolo ordinato; una crescita lenta produce spesso cristalli più grandi.',
  'A catalyst provides a lower-activation-energy pathway for 2 H₂O₂ → 2 H₂O + O₂. Detergent traps oxygen as foam; the catalyst changes rate but is not consumed overall.': 'Un catalizzatore offre un percorso a minore energia di attivazione per 2 H₂O₂ → 2 H₂O + O₂. Il detergente intrappola l’ossigeno nella schiuma; il catalizzatore modifica la velocità ma non viene consumato nel bilancio complessivo.',
  'It demonstrates electrode half-reactions, atom conservation and conversion of electrical energy into chemical energy.': 'Dimostra le semireazioni agli elettrodi, la conservazione degli atomi e la conversione di energia elettrica in energia chimica.',
  'It makes acid–base equilibria visible; it is qualitative and does not replace a calibrated pH meter.': 'Rende visibili gli equilibri acido–base; è qualitativo e non sostituisce un pHmetro calibrato.',
  'It connects proton transfer, gas evolution and the role of product removal as a driving force.': 'Collega trasferimento protonico, sviluppo di gas e rimozione di un prodotto come forza motrice.',
  'It makes coupled electron transfer and relative metal reactivity directly observable.': 'Rende direttamente osservabili il trasferimento elettronico accoppiato e la reattività relativa dei metalli.',
  'It links macroscopic crystal shape to solubility, nucleation and microscopic periodic order.': 'Collega la forma macroscopica dei cristalli a solubilità, nucleazione e ordine periodico microscopico.',
  'It distinguishes kinetics from stoichiometric yield and reveals an exothermic catalytic process.': 'Distingue la cinetica dalla resa stechiometrica e mostra un processo catalitico esotermico.',
  'Low-voltage DC · inert electrodes': 'Corrente continua a bassa tensione · elettrodi inerti','Electricity': 'Elettricità','Red cabbage · household samples': 'Cavolo rosso · campioni domestici','Mixing': 'Miscelazione','Vinegar · sodium bicarbonate': 'Aceto · bicarbonato di sodio','Iron · dilute CuSO₄ solution': 'Ferro · soluzione diluita di CuSO₄','Contact': 'Contatto','Table salt or alum · water': 'Sale da cucina o allume · acqua','Cooling / evaporation': 'Raffreddamento / evaporazione','3% H₂O₂ · detergent · yeast': 'H₂O₂ al 3% · detergente · lievito','Catalyst': 'Catalizzatore',
  'Add a small amount of inert electrolyte to water in a transparent vessel.': 'Aggiungi all’acqua una piccola quantità di elettrolita inerte in un recipiente trasparente.','Insert two inert electrodes without letting them touch.': 'Inserisci due elettrodi inerti senza farli toccare.','Connect to a current-limited DC source and collect the gases separately in inverted water-filled tubes.': 'Collega una sorgente continua a corrente limitata e raccogli separatamente i gas in provette capovolte piene d’acqua.','Compare gas volumes; interpret with the balanced equation.': 'Confronta i volumi dei gas e interpretali mediante l’equazione bilanciata.',
  'Steep chopped red cabbage in hot water, cool and filter the purple extract.': 'Lascia il cavolo rosso tritato in acqua calda, raffredda e filtra l’estratto viola.','Place equal portions in labeled clear cups.': 'Distribuisci porzioni uguali in bicchieri trasparenti etichettati.','Add one separate sample per cup, such as lemon juice, water or bicarbonate solution.': 'Aggiungi un solo campione per bicchiere, per esempio succo di limone, acqua o soluzione di bicarbonato.','Record colors against a control; do not return tested liquids to containers.': 'Confronta i colori con il controllo; non riversare i liquidi nei contenitori originali.',
  'Place a measured spoonful of sodium bicarbonate in a wide container.': 'Metti una quantità misurata di bicarbonato di sodio in un contenitore largo.','Add a measured small volume of vinegar.': 'Aggiungi un piccolo volume misurato di aceto.','Observe fizzing and, optionally, capture CO₂ in a loosely fitted balloon.': 'Osserva l’effervescenza e, facoltativamente, raccogli la CO₂ in un palloncino applicato senza tenuta rigida.','Write the molecular and net ionic descriptions; compare initial and final mass only in a properly designed closed system.': 'Scrivi l’equazione molecolare e quella ionica netta; confronta le masse solo in un sistema chiuso progettato correttamente.',
  'Clean an iron nail with abrasive material and record its appearance.': 'Pulisci un chiodo di ferro con materiale abrasivo e annotane l’aspetto.','Immerse it in a labeled dilute copper(II) sulfate solution.': 'Immergilo in una soluzione diluita ed etichettata di solfato di rame(II).','Wait without stirring, then compare coating and solution color.': 'Attendi senza agitare, poi confronta il deposito e il colore della soluzione.','Remove with forceps, rinse into the waste container and dispose through an approved route.': 'Rimuovi con pinze, risciacqua nel contenitore dei rifiuti e smaltisci secondo una procedura approvata.',
  'Add solute gradually to hot water until a small amount no longer dissolves.': 'Aggiungi gradualmente il soluto all’acqua calda finché una piccola quantità non si scioglie più.','Decant or filter the clear saturated solution into a clean jar.': 'Travasa o filtra la soluzione satura limpida in un vaso pulito.','Suspend a seed crystal or rough thread without touching the walls.': 'Sospendi un cristallo-seme o un filo ruvido senza toccare le pareti.','Cover loosely, leave undisturbed and record growth over several days.': 'Copri senza sigillare, lascia indisturbato e registra la crescita per alcuni giorni.',
  'Place the open bottle or cylinder in a tray and add a little dish detergent.': 'Metti il recipiente aperto in un vassoio e aggiungi poco detersivo per piatti.','Prepare a yeast suspension in lukewarm water as the catalase source.': 'Prepara una sospensione di lievito in acqua tiepida come fonte di catalasi.','Add the suspension and step back from the rising foam.': 'Aggiungi la sospensione e allontanati dalla schiuma in crescita.','Feel warmth only indirectly at the vessel exterior; relate O₂ production to the balanced equation.': 'Rileva il calore soltanto indirettamente sulla parete esterna; collega la produzione di O₂ all’equazione bilanciata.'
});

Object.assign(IT, {
  'Use a current-limited low-voltage source; never use mains electricity or ignite collected gas.':'Usa una sorgente a bassa tensione con corrente limitata; mai la rete elettrica e mai incendiare i gas raccolti.',
  'Do not mix household cleaners with one another; especially never combine bleach with acids or ammonia.':'Non mescolare detergenti domestici fra loro; soprattutto mai candeggina con acidi o ammoniaca.',
  'Use small quantities in an open container; never cap or seal a gas-producing mixture.':'Usa piccole quantità in un contenitore aperto; non chiudere mai una miscela che produce gas.',
  'Copper sulfate is harmful to people and aquatic life; use a controlled protocol and collect all waste.':'Il solfato di rame è nocivo per persone e vita acquatica; usa un protocollo controllato e raccogli tutti i rifiuti.',
  'Use heat-resistant glassware and protect against hot water; crystals are not food after laboratory handling.':'Usa vetreria resistente al calore e proteggiti dall’acqua calda; dopo l’esperimento i cristalli non sono commestibili.',
  'Use only household 3% peroxide, small quantities, eye protection and an open tray; the vessel may warm.':'Usa soltanto perossido domestico al 3%, piccole quantità, protezione oculare e un vassoio aperto; il recipiente può scaldarsi.',
  'First classify':'Prima classifica','Ionic: formula → name':'Ionico: formula → nome','Ionic: name → formula':'Ionico: nome → formula','Variable-charge metals':'Metalli a carica variabile','Molecular: formula → name':'Molecolare: formula → nome','Molecular: name → formula':'Molecolare: nome → formula','Acids':'Acidi','Hydrates and states':'Idrati e stati fisici',
  'Metal + non-metal or polyatomic ion?':'Metallo + non metallo o ione poliatomico?','Two non-metals?':'Due non metalli?','Formula begins H and is aqueous? Often an':'La formula inizia con H ed è acquosa? Spesso è un','This first decision chooses the naming system.':'Questa prima decisione determina il sistema di nomenclatura.',
  'Read the cation, then the anion. Monatomic anions take':'Leggi prima il catione, poi l’anione. Gli anioni monoatomici prendono','Keep polyatomic names unchanged:':'Mantieni invariati i nomi degli ioni poliatomici:','No numerical prefixes.':'Nessun prefisso numerico.',
  'Write ion charges, then choose the lowest subscripts giving net charge zero:':'Scrivi le cariche ioniche, poi scegli i minimi pedici che danno carica netta zero:','Use parentheses when several polyatomic ions are needed:':'Usa le parentesi quando occorrono più ioni poliatomici:',
  'Infer metal charge from the anion and state it as a Roman numeral:':'Ricava la carica del metallo dall’anione e indicala con un numero romano:','Iron(II) oxide would be FeO.':'L’ossido di ferro(II) sarebbe FeO.',
  'Use prefixes for atom counts; normally omit mono- on the first element.':'Usa i prefissi per il numero di atomi; normalmente ometti mono- sul primo elemento.','The second element takes -ide:':'Il secondo elemento assume il suffisso appropriato:','Prefixes become subscripts directly—never “balance charges”:':'I prefissi diventano direttamente pedici: non “bilanciare le cariche”:','The (aq) state matters.':'Lo stato (aq) è determinante.','State symbols:':'Simboli di stato:','solid':'solido','liquid':'liquido','gas':'gas','dissolved in water':'disciolto in acqua'
});

Object.assign(IT,{
 'ELEMENT':'ELEMENTO','NUCLEUS':'NUCLEO','ELECTRON SHELLS':'GUSCI ELETTRONICI','WHERE IT APPEARS':'DOVE SI TROVA','COMMON PARTNERS':'PARTNER COMUNI','ABUNDANCE SNAPSHOT':'ABBONDANZA INDICATIVA','protons · about':'protoni · circa','neutrons in a representative isotope':'neutron in un isotopo rappresentativo','electrons (simplified neutral atom)':'elettroni (atomo neutro semplificato)','Notable isotopes:':'Isotopi notevoli:','Several stable or radioactive isotopes; explore isotope charts for detail.':'Diversi isotopi stabili o radioattivi; consulta una carta degli isotopi per i dettagli.','The circular Bohr-style model is a learning aid. Real electrons occupy probability distributions (orbitals), not miniature planetary paths.':'Il modello circolare in stile Bohr è un ausilio didattico. Gli elettroni reali occupano distribuzioni di probabilità (orbitali), non piccole orbite planetarie.','stars and water':'stelle e acqua','living matter, carbonates and fuels':'materia vivente, carbonati e combustibili','air, water and rocks':'aria, acqua e rocce','silicate rocks and electronics':'rocce silicatiche ed elettronica','ores, Earth’s core and blood':'minerali, nucleo terrestre e sangue','minerals, materials or trace natural sources':'minerali, materiali o sorgenti naturali in tracce','most elements':'la maggior parte degli elementi','partners predicted by valence electrons':'partner previsti dagli elettroni di valenza','abundance varies strongly by environment':'l’abbondanza varia molto secondo l’ambiente','Highly context-dependent':'Fortemente dipendente dal contesto','Earth crust':'crosta terrestre','Universe by mass':'Universo in massa','isotope-weighted average':'media ponderata degli isotopi',
 'START CONDITIONS MATTER':'LE CONDIZIONI DI AVVIO CONTANO','Heat, light, electricity, concentration, pressure, catalysts or simple contact can supply activation energy or open a reaction pathway.':'Calore, luce, elettricità, concentrazione, pressione, catalizzatori o semplice contatto possono fornire energia di attivazione o aprire un percorso di reazione.','The outer electron leaves sodium and is accepted by chlorine. Opposite ions then attract.':'L’elettrone esterno lascia il sodio ed è accettato dal cloro. Gli ioni di carica opposta si attraggono.','A proton moves from the acid to a base; the electron pair remains with chloride.':'Un protone passa dall’acido alla base; la coppia elettronica rimane al cloruro.','Hydrated ions diffuse together and form an insoluble ionic lattice: the precipitate.':'Gli ioni idratati diffondono l’uno verso l’altro e formano un reticolo ionico insolubile: il precipitato.','Old covalent bonds break and electron pairs reorganize into new bonds.':'I vecchi legami covalenti si rompono e le coppie elettroniche si riorganizzano in nuovi legami.','These four headings are useful teaching categories, not mutually exclusive fundamental classes: for example, combustion is both redox and bond rearrangement, while neutralization is proton transfer and may also be described by ion exchange.':'Queste quattro categorie sono utili didatticamente, ma non sono classi fondamentali mutuamente esclusive: per esempio la combustione è sia redox sia riarrangiamento di legami; la neutralizzazione è trasferimento protonico e può anche essere descritta come scambio ionico.'
});

Object.assign(IT,{
 'Balanced coefficients are chemical bookkeeping. They let laboratories predict reactant quantities, product yields, waste, energy and cost—from a school flask to an industrial reactor.':'I coefficienti bilanciati sono la contabilità della chimica. Permettono di prevedere quantità di reagenti, rese, scarti, energia e costi, da un piccolo recipiente a un reattore industriale.','“In a chemical reaction, matter is neither created nor destroyed.” — Lavoisier’s law of conservation of mass':'«In una reazione chimica la materia non si crea né si distrugge.» — Legge di conservazione della massa di Lavoisier','Forming water':'Formazione dell’acqua','Rust formation':'Formazione della ruggine','Propane combustion':'Combustione del propano','Aluminium sulfate':'Solfato di alluminio','STEP':'PASSO','OF':'DI','INVENTORY':'INVENTARIO','BALANCE ONE PART':'BILANCIA UNA PARTE','RECOUNT':'RICONTA','VERIFY':'VERIFICA','Write correct formulas. Subscripts belong to substances and must never be changed.':'Scrivi formule corrette. I pedici appartengono alle sostanze e non devono mai essere modificati.','Put 2 before H₂O: oxygen is now balanced, but hydrogen is not.':'Metti 2 davanti a H₂O: ora l’ossigeno è bilanciato, ma l’idrogeno no.','Put 2 before H₂: both H and O now match.':'Metti 2 davanti a H₂: ora coincidono sia H sia O.','Reduce if possible, then verify every atom. Ratio 2:1:2 is final.':'Riduci se possibile, poi verifica ogni atomo. Il rapporto finale è 2:1:2.','Inventory iron and oxygen. Both mismatch.':'Conta ferro e ossigeno. Entrambi non coincidono.','Make product oxygen even: 2 Fe₂O₃ contains 6 O.':'Rendi pari l’ossigeno nei prodotti: 2 Fe₂O₃ contiene 6 O.','Use 3 O₂ to supply 6 O on the left.':'Usa 3 O₂ per ottenere 6 O a sinistra.','Use 4 Fe. Final ratio 4:3:2.':'Usa 4 Fe. Rapporto finale 4:3:2.','Start with C and H; leave elemental oxygen until last.':'Inizia da C e H; lascia per ultimo l’ossigeno elementare.','Use 3 CO₂ to balance three carbon atoms.':'Usa 3 CO₂ per bilanciare tre atomi di carbonio.','Use 4 H₂O to balance eight hydrogen atoms.':'Usa 4 H₂O per bilanciare otto atomi di idrogeno.','Products contain 10 O, so use 5 O₂. Ratio 1:5:3:4.':'I prodotti contengono 10 O: usa quindi 5 O₂. Rapporto 1:5:3:4.','Because sulfate stays intact, count SO₄ as a reusable unit.':'Poiché il solfato resta intatto, conta SO₄ come unità.','Use 3 H₂SO₄ to provide three sulfates.':'Usa 3 H₂SO₄ per fornire tre solfati.','Use 2 Al to match Al₂.':'Usa 2 Al per corrispondere ad Al₂.','Use 3 H₂ to match six hydrogens; then expand SO₄ to verify S and O.':'Usa 3 H₂ per ottenere sei idrogeni; poi espandi SO₄ per verificare S e O.',
 'Just as “a dozen” means 12 objects, one mole means exactly 6.02214076 × 10²³ specified entities. It bridges invisible particles and measurable laboratory mass.':'Come “una dozzina” significa 12 oggetti, una mole indica esattamente 6,02214076 × 10²³ entità specificate. Collega particelle invisibili e massa misurabile.','entities per mole · Avogadro constant, exact':'entità per mole · costante di Avogadro, esatta','A symbolic “jar” of microscopic entities':'Un “recipiente” simbolico di entità microscopiche','molecules':'molecole','of water':'di acqua','Moles = mass ÷ molar mass':'Moli = massa ÷ massa molare','Formula mass is the sum of each atom’s atomic mass. Multiplying moles by Avogadro’s constant gives the number of molecules or formula units.':'La massa formula è la somma delle masse atomiche. Moltiplicando le moli per la costante di Avogadro si ottiene il numero di molecole o unità formula.','Core school-level rules; systematic names can become more detailed.':'Regole fondamentali; i nomi sistematici possono richiedere ulteriori dettagli.','What is the correct name for Fe₂O₃?':'Qual è il nome corretto di Fe₂O₃?','Iron oxide':'Ossido di ferro','Iron(II) oxide':'Ossido di ferro(II)','Iron(III) oxide':'Ossido di ferro(III)',
 'Each static apparatus diagram is paired with a recipe-style outline, the expected observation and the chemical interpretation. Use established, risk-assessed procedures, suitable PPE and responsible disposal.':'Ogni schema statico dell’apparato è accompagnato da procedura, osservazione attesa e interpretazione chimica. Usa procedure consolidate e valutate per il rischio, protezioni adeguate e smaltimento responsabile.','Use the safest available household-scale materials where indicated. Wear eye protection, label every substance, ventilate appropriately, control ignition sources and never seal a gas-producing reaction.':'Quando indicato, usa i materiali domestici più sicuri disponibili. Proteggi gli occhi, etichetta ogni sostanza, ventila adeguatamente, controlla le fonti di accensione e non sigillare mai una reazione che produce gas.','simplified models for learning':'modelli semplificati per l’apprendimento','not a substitute for laboratory supervision':'non sostituisce un’adeguata supervisione di laboratorio'
});

function addElementNames(en,it){en.split('|').forEach((n,i)=>IT[n]=it.split('|')[i])}

Object.assign(IT, {
  'neutrons in a representative isotope':'neutroni in un isotopo rappresentativo',
  '1 protons · about 0 neutrons in a representative isotope':'1 protone · circa 0 neutroni in un isotopo rappresentativo',
  '1 electrons (simplified neutral atom)':'1 elettrone (atomo neutro semplificato)',
  '¹H protium · ²H deuterium · ³H tritium':'¹H protio · ²H deuterio · ³H trizio',
  'Acid–base':'Acido–base',
  'Metathesis':'Metatesi',
  'Combination · decomposition · substitution':'Combinazione · decomposizione · sostituzione',
  'mol of':'mol di',
  'mol of Water':'mol di Acqua',
  'of Water':'di Acqua',
  'Ionic':'Ionico',
  'Molecular':'Molecolare',
  'acid':'acido',
  'sodium chloride':'cloruro di sodio',
  'calcium carbonate':'carbonato di calcio',
  'aluminium oxide':'ossido di alluminio',
  'calcium nitrate':'nitrato di calcio',
  'Fe₂O₃ has 3 × O²⁻ = −6, so 2 Fe total +6:':'Fe₂O₃ contiene 3 × O²⁻ = −6, quindi i 2 Fe devono totalizzare +6:',
  'iron(III) oxide':'ossido di ferro(III)',
  'carbon monoxide':'monossido di carbonio',
  'carbon dioxide':'diossido di carbonio',
  'dinitrogen tetroxide':'tetrossido di diazoto',
  'sulfur hexafluoride':'esafluoruro di zolfo',
  'dinitrogen pentoxide':'pentossido di diazoto',
  'Prefixes:':'Prefissi:',
  'HCl(aq): hydrochloric acid. Anion':'HCl(aq): acido cloridrico. L’anione',
  '-ate → -ic acid':'-ato → acido -ico',
  '-ite → -ous acid':'-ito → acido -oso',
  'nitrate → nitric':'nitrato → nitrico',
  'nitrite → nitrous':'nitrito → nitroso',
  'copper(II) sulfate pentahydrate':'solfato di rame(II) pentaidrato',
  'sodium':'sodio','calcium':'calcio','aluminium':'alluminio','ammonium':'ammonio',
  'chloride':'cloruro','oxide':'ossido','sulfide':'solfuro','nitride':'nitruro',
  'hydroxide':'idrossido','nitrate':'nitrato','nitrite':'nitrito','carbonate':'carbonato',
  'sulfate':'solfato','sulfite':'solfito','phosphate':'fosfato',
  'classify → identify ions or count atoms → apply the matching rule → check charge neutrality or prefixes.':'classifica → identifica gli ioni o conta gli atomi → applica la regola corretta → verifica la neutralità della carica o i prefissi.',
  'Correct — three O²⁻ ions total −6, so two iron ions must total +6: each is Fe³⁺.':'Corretto: tre ioni O²⁻ totalizzano −6, quindi i due ioni ferro devono totalizzare +6; ciascuno è Fe³⁺.',
  'Not quite. Use oxide as O²⁻, total the negative charge, then infer the iron oxidation state.':'Non ancora. Considera l’ossido come O²⁻, somma la carica negativa e ricava lo stato di ossidazione del ferro.',
  'CATHODE':'CATODO','ANODE':'ANODO','volumes':'volumi','volume':'volume',
  'CO₂ expands the foam':'La CO₂ espande la schiuma','Fe nail':'Chiodo di Fe','Cu deposit':'Deposito di Cu',
  'ordered lattice grows from nuclei':'il reticolo ordinato cresce dai nuclei',
  'O₂ foam + released heat':'Schiuma di O₂ + calore liberato'
});
addElementNames('Hydrogen|Helium|Lithium|Beryllium|Boron|Carbon|Nitrogen|Oxygen|Fluorine|Neon|Sodium|Magnesium|Aluminium|Silicon|Phosphorus|Sulfur|Chlorine|Argon|Potassium|Calcium|Scandium|Titanium|Vanadium|Chromium|Manganese|Iron|Cobalt|Nickel|Copper|Zinc|Gallium|Germanium|Arsenic|Selenium|Bromine|Krypton|Rubidium|Strontium|Yttrium|Zirconium','Idrogeno|Elio|Litio|Berillio|Boro|Carbonio|Azoto|Ossigeno|Fluoro|Neon|Sodio|Magnesio|Alluminio|Silicio|Fosforo|Zolfo|Cloro|Argon|Potassio|Calcio|Scandio|Titanio|Vanadio|Cromo|Manganese|Ferro|Cobalto|Nichel|Rame|Zinco|Gallio|Germanio|Arsenico|Selenio|Bromo|Kripton|Rubidio|Stronzio|Ittrio|Zirconio');

addElementNames('Niobium|Molybdenum|Technetium|Ruthenium|Rhodium|Palladium|Silver|Cadmium|Indium|Tin|Antimony|Tellurium|Iodine|Xenon|Caesium|Barium|Lanthanum|Cerium|Praseodymium|Neodymium|Promethium|Samarium|Europium|Gadolinium|Terbium|Dysprosium|Holmium|Erbium|Thulium|Ytterbium|Lutetium|Hafnium|Tantalum|Tungsten|Rhenium|Osmium|Iridium|Platinum|Gold|Mercury','Niobio|Molibdeno|Tecnezio|Rutenio|Rodio|Palladio|Argento|Cadmio|Indio|Stagno|Antimonio|Tellurio|Iodio|Xeno|Cesio|Bario|Lantanio|Cerio|Praseodimio|Neodimio|Promezio|Samario|Europio|Gadolinio|Terbio|Disprosio|Olmio|Erbio|Tulio|Itterbio|Lutezio|Afnio|Tantalio|Tungsteno|Renio|Osmio|Iridio|Platino|Oro|Mercurio');

addElementNames('Thallium|Lead|Bismuth|Polonium|Astatine|Radon|Francium|Radium|Actinium|Thorium|Protactinium|Uranium|Neptunium|Plutonium|Americium|Curium|Berkelium|Californium|Einsteinium|Fermium|Mendelevium|Nobelium|Lawrencium','Tallio|Piombo|Bismuto|Polonio|Astato|Radon|Francio|Radio|Attinio|Torio|Protoattinio|Uranio|Nettunio|Plutonio|Americio|Curio|Berkelio|Californio|Einsteinio|Fermio|Mendelevio|Nobelio|Laurenzio');

addElementNames('Rutherfordium|Dubnium|Seaborgium|Bohrium|Hassium|Meitnerium|Darmstadtium|Roentgenium|Copernicium|Nihonium|Flerovium|Moscovium|Livermorium|Tennessine|Oganesson','Rutherfordio|Dubnio|Seaborgio|Bohrio|Hassio|Meitnerio|Darmstadtio|Roentgenio|Copernicio|Nihonio|Flerovio|Moscovio|Livermorio|Tennesso|Oganesson');

addElementNames('Water|Oxygen|Nitrogen|Carbon dioxide|Ozone|Ammonia|Hydrogen peroxide|Methane|Hydrochloric acid|Sulfuric acid|Nitric acid|Acetic acid|Carbonic acid|Phosphoric acid|Sodium hydroxide|Calcium hydroxide|Potassium hydroxide|Magnesium hydroxide|Sodium bicarbonate|Sodium chloride|Calcium carbonate|Copper sulfate|Potassium nitrate|Calcium phosphate|Iron oxide|Silicon dioxide|Sodium carbonate|Magnesium sulfate|Silver nitrate|Glucose|Ethanol','Acqua|Ossigeno|Azoto|Anidride carbonica|Ozono|Ammoniaca|Perossido di idrogeno|Metano|Acido cloridrico|Acido solforico|Acido nitrico|Acido acetico|Acido carbonico|Acido fosforico|Idrossido di sodio|Idrossido di calcio|Idrossido di potassio|Idrossido di magnesio|Bicarbonato di sodio|Cloruro di sodio|Carbonato di calcio|Solfato di rame|Nitrato di potassio|Fosfato di calcio|Ossido di ferro|Diossido di silicio|Carbonato di sodio|Solfato di magnesio|Nitrato d’argento|Glucosio|Etanolo');

addElementNames('Sucrose|Acetone|Urea|Glycerol|Acetylene|Benzene|Citric acid|Lactic acid|Glycine|Caffeine|Aspirin|Cholesterol|Triglyceride (triolein)|ATP|Vitamin C|DNA base adenine|Propane|Butane|Ethylene|Sulfur dioxide|Carbon monoxide|Titanium dioxide|Aluminium oxide|Calcium oxide|Sodium hypochlorite|Hydrogen|Lithium cobalt oxide|Sulfur hexafluoride|Nitrous oxide|Lead sulfate','Saccarosio|Acetone|Urea|Glicerolo|Acetilene|Benzene|Acido citrico|Acido lattico|Glicina|Caffeina|Aspirina|Colesterolo|Trigliceride (trioleina)|ATP|Vitamina C|Base del DNA adenina|Propano|Butano|Etilene|Diossido di zolfo|Monossido di carbonio|Diossido di titanio|Ossido di alluminio|Ossido di calcio|Ipoclorito di sodio|Idrogeno|Ossido di litio e cobalto|Esafluoruro di zolfo|Protossido di azoto|Solfato di piombo');

function bondClarifier() {
  const box = document.getElementById('molinfo');
  if (!box || box.querySelector('.bond-clarifier')) return;
  const it = document.getElementById('language').value === 'it';
  const acid = selected.fam === 'Acids';
  const ionic = selected.bond === 'ionic';
  const structured = !!structureSpec[selected.formula];
  let en, ita;
  if (acid && !structured) {
    en = '<b>Why are no bonds drawn here?</b> An acid formula does not by itself specify the physical state. Pure HCl, HNO₃ or H₂SO₄ are molecular substances with covalent bonds; in water they transfer protons to H₂O and form solvated ions to an extent that depends on acid strength. A single ball-and-stick picture would therefore conflate the pure molecular species with the aqueous ionic system.';
    ita = '<b>Perché qui non sono disegnati legami?</b> La formula di un acido non specifica da sola lo stato fisico. HCl, HNO₃ o H₂SO₄ puri sono sostanze molecolari con legami covalenti; in acqua trasferiscono protoni a H₂O e formano ioni solvatati in misura dipendente dalla forza dell’acido. Un unico modello a sfere confonderebbe quindi la specie molecolare pura con il sistema ionico acquoso.';
  } else if (ionic && structured) {
    en = '<b>What does the dashed line mean?</b> It marks electrostatic attraction between oppositely charged ions, not a localized shared-electron bond. The isolated ion pair is only a teaching symbol: in a solid salt, each ion belongs to an extended lattice and interacts with several neighbours.';
    ita = '<b>Che cosa significa la linea tratteggiata?</b> Indica l’attrazione elettrostatica tra ioni di carica opposta, non un legame localizzato basato sulla condivisione di elettroni. La coppia isolata è solo un simbolo didattico: in un sale cristallino ogni ione appartiene a un reticolo esteso e interagisce con più vicini.';
  } else if (ionic) {
    en = '<b>Why are no individual ionic bonds drawn?</b> This formula describes the smallest electrically neutral ratio in an extended crystal lattice, not a discrete molecule. Each ion interacts electrostatically with several neighbours; drawing one isolated pair would be misleading.';
    ita = '<b>Perché non sono disegnati singoli legami ionici?</b> La formula descrive il minimo rapporto elettricamente neutro in un reticolo cristallino esteso, non una molecola discreta. Ogni ione interagisce elettrostaticamente con più vicini; disegnare una coppia isolata sarebbe fuorviante.';
  } else if (structured) {
    en = '<b>How should the lines be read?</b> A solid line represents one covalent bond; parallel lines represent formal double or triple bonds. A solid-plus-dashed pair marks equivalent, resonance-delocalized bonding. These are simplified two-dimensional structural conventions, not literal sticks between atoms.';
    ita = '<b>Come si leggono le linee?</b> Una linea continua rappresenta un legame covalente; linee parallele rappresentano formalmente legami doppi o tripli. Una coppia continua-tratteggiata indica legami equivalenti delocalizzati per risonanza. Sono convenzioni strutturali bidimensionali semplificate, non bastoncini reali fra gli atomi.';
  } else {
    en = '<b>Why is there no bond network?</b> The molecular formula fixes elemental composition but may correspond to different constitutional isomers, stereoisomers or extended structures. Unless a verified structure is encoded, this atlas shows exact composition and deliberately does not invent connectivity or bond order.';
    ita = '<b>Perché non compare una rete di legami?</b> La formula molecolare fissa la composizione elementare ma può corrispondere a diversi isomeri costituzionali, stereoisomeri o strutture estese. Se non è codificata una struttura verificata, l’atlante mostra la composizione esatta e non inventa connettività o ordine di legame.';
  }
  box.insertAdjacentHTML('beforeend', `<div class="scientific-note bond-clarifier no-auto-translate">${it ? ita : en}</div>`);
}

new MutationObserver(() => bondClarifier()).observe(document.getElementById('molinfo'), {childList:true});
bondClarifier();
document.getElementById('language').addEventListener('change', () => {
  document.querySelector('.bond-clarifier')?.remove();
  bondClarifier();
  setTimeout(() => translateTree(), 0);
});

Object.assign(IT, {
  'covalent bond · solid line':'legame covalente · linea continua',
  'double/triple bonds · parallel lines':'legami doppi/tripli · linee parallele',
  'resonance-delocalized bond · solid + dashed':'legame delocalizzato per risonanza · continuo + tratteggiato',
  'ionic attraction · dashed amber line':'attrazione ionica · linea ambra tratteggiata',
  'Lines are a bonding key, not a distance scale.':'Le linee costituiscono una legenda dei legami, non una scala delle distanze.'
});

/* Complete UI/data audit: static labels, attributes and every molecular-library description. */
Object.assign(IT, {
  'Color follows the warm poster logic of your reference: oranges for metals, golds for non-metals, blue-grey for uncertain synthetic chemistry, and olive for the f-block.':'I colori riprendono la logica calda del poster di riferimento: arancione per i metalli, oro per i non metalli, grigio-azzurro per gli elementi sintetici dalla chimica meno definita e verde oliva per il blocco f.',
  'Alkali metals':'Metalli alcalini','Metals':'Metalli','Metalloids':'Semimetalli','Non-metals':'Non metalli','f-block':'blocco f','Synthetic / uncertain':'Sintetici / proprietà incerte',
  'atomic number':'numero atomico','Close':'Chiudi','Language':'Lingua','Try water, CaCO3, glucose…':'Prova acqua, CaCO3, glucosio…',
  'Covalent substances may form molecules; ionic and metallic substances form extended lattices, represented here by a small illustrative unit.':'Le sostanze covalenti possono formare molecole; quelle ioniche e metalliche formano reticoli estesi, qui rappresentati mediante una piccola unità illustrativa.',
  'Everyday & atmospheric':'Uso quotidiano e atmosfera','Bases':'Basi','Salts & minerals':'Sali e minerali','Organic molecules':'Molecole organiche','Biomolecules':'Biomolecole','Industrial & materials':'Industria e materiali','Energy & electrochemistry':'Energia ed elettrochimica',
  'covalent substance':'sostanza covalente','ionic substance':'sostanza ionica','covalent':'covalente','ionic':'ionico','substance':'sostanza','formula units':'unità formula','Every atom in':'Ogni atomo in','is counted; no connectivity or geometry is implied.':'è conteggiato; non si presuppongono connettività né geometria.',
  'Essential solvent; covers most of Earth':'Solvente essenziale; ricopre gran parte della Terra','Gas used in respiration':'Gas utilizzato nella respirazione','Main component of air':'Componente principale dell’aria','Respiration product and greenhouse gas':'Prodotto della respirazione e gas serra','Stratospheric UV shield':'Schermo stratosferico contro i raggi UV','Fertilizers and cleaners':'Fertilizzanti e detergenti','Oxidizer and antiseptic':'Ossidante e antisettico','Natural gas; strong greenhouse gas':'Gas naturale; potente gas serra',
  'Stomach acid and laboratory reagent':'Acido gastrico e reagente di laboratorio','Batteries and industry':'Batterie e industria','Fertilizers and nitration':'Fertilizzanti e nitrazione','The acid in vinegar':'L’acido presente nell’aceto','Carbonated water chemistry':'Chimica dell’acqua gassata','Food and fertilizer chemistry':'Chimica alimentare e dei fertilizzanti',
  'Soap making and drain cleaner':'Produzione di sapone e disgorganti','Limewater and mortar':'Acqua di calce e malta','Alkaline batteries and soap':'Batterie alcaline e sapone','Milk of magnesia':'Latte di magnesia','Baking soda; a mild base':'Bicarbonato alimentare; una base debole',
  'Table salt and seawater':'Sale da cucina e acqua marina','Limestone, chalk and marble':'Calcare, gesso e marmo','Blue crystals used in school labs':'Cristalli blu utilizzati nei laboratori didattici','Fertilizer and oxidizer':'Fertilizzante e ossidante','Bones, teeth and phosphate rock':'Ossa, denti e rocce fosfatiche','Rust pigment and iron ore':'Pigmento della ruggine e minerale di ferro','Quartz, sand and glass':'Quarzo, sabbia e vetro','Washing soda and glass':'Soda da bucato e vetro','Epsom salt':'Sale di Epsom','Precipitation tests and photography':'Saggi di precipitazione e fotografia',
  'Cellular fuel and photosynthesis product':'Combustibile cellulare e prodotto della fotosintesi','Alcoholic drinks, solvent and fuel':'Bevande alcoliche, solvente e combustibile','Table sugar':'Zucchero da tavola','Common solvent':'Solvente comune','Nitrogen waste and fertilizer':'Scarto azotato e fertilizzante','Backbone of triglycerides':'Struttura portante dei trigliceridi','Welding fuel with a triple bond':'Combustibile per saldatura con un triplo legame','Aromatic ring; industrial feedstock':'Anello aromatico; materia prima industriale','Citrus fruits and metabolism':'Agrumi e metabolismo','Fermentation and muscle metabolism':'Fermentazione e metabolismo muscolare',
  'Simplest amino acid':'L’amminoacido più semplice','Natural stimulant':'Stimolante naturale','Pain relief medicine':'Farmaco analgesico','Membrane lipid and hormone precursor':'Lipide di membrana e precursore ormonale','Representative dietary fat':'Grasso alimentare rappresentativo','Cellular energy-transfer molecule':'Molecola per il trasferimento di energia cellulare','Antioxidant nutrient':'Nutriente antiossidante','One nucleobase in genetic material':'Una base azotata del materiale genetico',
  'Bottled fuel':'Combustibile in bombola','Lighter fuel':'Combustibile per accendini','Makes polyethylene':'Serve a produrre polietilene','Industrial gas and air pollutant':'Gas industriale e inquinante atmosferico','Toxic product of incomplete combustion':'Prodotto tossico della combustione incompleta','White pigment and sunscreen':'Pigmento bianco e filtro solare','Corundum, ceramics and protective films':'Corindone, ceramiche e rivestimenti protettivi','Quicklime and cement':'Calce viva e cemento','Household bleach':'Candeggina domestica',
  'Fuel cells and star fuel':'Celle a combustibile e combustibile delle stelle','Lithium-ion battery cathode':'Catodo delle batterie agli ioni di litio','Electrical insulator; potent greenhouse gas':'Isolante elettrico; potente gas serra','Anaesthetic and greenhouse gas':'Anestetico e gas serra','Lead-acid battery discharge product':'Prodotto di scarica delle batterie al piombo',
  'O and metals':'O e metalli','metals':'metalli','Universe':'Universo','dating':'datazione',
  'Contact plus sufficient activation energy':'Contatto ed energia di attivazione sufficiente','Dissolving and mixing in water':'Dissoluzione e miscelazione in acqua','Mix two soluble ionic solutions':'Mescola due soluzioni ioniche solubili','Light supplies activation energy':'La luce fornisce energia di attivazione',
  'combustion':'combustione','corrosion':'corrosione','batteries':'batterie','photosynthesis':'fotosintesi','cellular respiration':'respirazione cellulare','vinegar + baking soda':'aceto e bicarbonato','neutralization':'neutralizzazione','antacid action':'azione antiacida','buffer systems':'sistemi tampone','precipitation tests':'saggi di precipitazione','water softening':'addolcimento dell’acqua','double displacement':'doppio scambio','gas-forming reactions':'reazioni con sviluppo di gas','polymerization':'polimerizzazione','thermal decomposition':'decomposizione termica','combination':'combinazione','substitution':'sostituzione',
  'one electron transfers → stable outer shells → ionic attraction':'un elettrone si trasferisce → gusci esterni stabili → attrazione ionica','H⁺ is donated; water accepts it to become H₃O⁺':'H⁺ viene ceduto; l’acqua lo accetta e diventa H₃O⁺','ions lock into a repeating AgCl solid lattice (precipitate)':'gli ioni si dispongono nel reticolo solido ripetitivo di AgCl (precipitato)','light weakens old bonds; atoms recombine into two HCl molecules':'la luce indebolisce i vecchi legami; gli atomi si ricombinano in due molecole di HCl',
  'molar mass':'massa molare','atoms per':'atomi per','CHOOSE AN EXERCISE':'SCEGLI UN ESERCIZIO','LIVE ATOM COUNT · LEFT : RIGHT':'CONTEGGIO ATOMI · SINISTRA : DESTRA',
  'A symbolic “jar” of microscopic entities':'Un “recipiente” simbolico di entità microscopiche','≈ 18.015 g of water':'≈ 18,015 g di acqua','formula units':'unità formula',
  'Starts:':'Avvio:','PROCEDURE OUTLINE':'PROCEDURA','Why it matters:':'Perché è importante:'
});
